Basic player movement
Team-Deadbytes/Casting-Shadows pull request #7
Opened 2017-12-04 13:30 UTC by hallur

Note: No rotation and no animation

2017-12-04 13:44 UTC, dadisigursveinn requested changes

2017-12-04 13:44 UTC, dadisigursveinn commented on Assets/Prefabs/Player.prefab
> +  m_TagString: Untagged
player prefab should be tagged

2017-12-04 13:44 UTC, dadisigursveinn commented on Assets/Prefabs/Player.prefab
> +Transform:
Prefab should be zeroed in world

2017-12-04 13:44 UTC, dadisigursveinn commented on Assets/Sprites/player.png.meta
> +    21300000: 1-player-right_foot_forward
not a fan of this convention.

Needs to be revisited with whole group

2017-12-04 13:47 UTC, hallur commented on Assets/Prefabs/Player.prefab
> +Transform:
Fixed

2017-12-04 13:48 UTC, dadisigursveinn approved these changes

2017-12-04 13:48 UTC, hallur commented on Assets/Prefabs/Player.prefab
> +  m_TagString: Untagged
Fixed

2017-12-04 13:48 UTC, merged

2017-12-05 01:24 UTC, dadisigursveinn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Player Movement](https://trello.com/c/kPGCLzh4/65-player-movement)